connectflow/users/models.py
from enum import unique
from turtle import position
from connectflow import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

# 사용자가 템플릿에서 인증되었는지를 확인
@login_manager.user_loader
def load_user(user_id) : 
    return User.query.get(user_id)

class User(db.Model, UserMixin): 
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(64), nullable=False, default='default_profile.png')
    status = db.Column(db.String(10), index=True)
    name = db.Column(db.String(10), index=True)
    title = db.Column(db.String(10), index=True)
    level = db.Column(db.String(10), index=True)
    position = db.Column(db.String(10), index=True)
    number_ktis = db.Column(db.String(7), unique=True, index=True)
    number_kt = db.Column(db.String(8), unique=True, index=True)
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    def __init__(self, name, number_ktis, email, password) : 
        self.name = name
        self.number_ktis = number_ktis
        self.email = email 
        self.password_hash = generate_password_hash(password)

    def check_password(self, password) : 
        return check_password_hash(self.password_hash, password)

    def __repr__(self) : 
        return f'[사용자] : {self.name}({self.number_ktis})'

connectflow/users/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import ValidationError, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from connectflow.users.models import User

# 로그인 폼
class LoginForm(FlaskForm): 
    number_ktis = StringField('아이디(사번)', validators=[DataRequired()])
    password = PasswordField('비밀번호', validators=[DataRequired()])
    submit = SubmitField('로그인')

# 회원가입 폼
class RegisterationForm(FlaskForm): 
    number_ktis = StringField('아이디(사번)', validators=[DataRequired()])
    name = StringField('성명', validators=[DataRequired()])
    email = StringField('이메일', validators=[DataRequired(), Email()])
    password = PasswordField('비밀번호', validators=[DataRequired(), EqualTo('password_confirm', message='비밀번호가 일치하지 않습니다.')])
    password_confirm = PasswordField('비밀번호 확인', validators=[DataRequired()])
    submit = SubmitField('회원가입')
    

connectflow/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

##########################
#### DATABASE SETUP ######
##########################
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

#########################
#### LOGIN CONFIGS ######
#########################
login_manager = LoginManager() 
login_manager.init_app(app)
login_manager.login_view = 'users.login'

#########################
#### BLUEPRINT SETUP ####
#########################
from connectflow.core.views import core
from connectflow.error.views import error
from connectflow.users.views import users
from connectflow.numbers.views import numbers
from connectflow.pservers.views import pservers
from connectflow.vservers.views import vservers
from connectflow.customers.views import customers
from connectflow.partners.views import partners
from connectflow.networks.views import networks
from connectflow.ap.views import ap

app.register_blueprint(core)
app.register_blueprint(error)
app.register_blueprint(users)
app.register_blueprint(numbers)
app.register_blueprint(pservers)
app.register_blueprint(vservers)
app.register_blueprint(customers)
app.register_blueprint(partners)
app.register_blueprint(networks)
app.register_blueprint(ap)

connectflow/ap/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

ap = Blueprint('ap', __name__)

@ap.route('/ap')
def frame(): 
    return render_template('ap.html')

connectflow/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index(): 
    return render_template('index.html')

connectflow/customers/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

customers = Blueprint('customers', __name__)

@customers.route('/customers')
def frame(): 
    return render_template('customers.html')

connectflow/networks/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

networks = Blueprint('networks', __name__)

@networks.route('/networks')
def frame(): 
    return render_template('networks.html')

connectflow/numbers/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

numbers = Blueprint('numbers', __name__)

@numbers.route('/numbers')
def frame(): 
    return render_template('numbers.html')

connectflow/partners/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

partners = Blueprint('partners', __name__)

@partners.route('/partners')
def frame(): 
    return render_template('partners.html')

connectflow/pservers/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

pservers = Blueprint('pservers', __name__)

@pservers.route('/pservers')
def frame(): 
    return render_template('pservers.html')

connectflow/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from connectflow import db
from connectflow.users.models import User
from connectflow.users.forms import LoginForm, RegisterationForm

users = Blueprint('users', __name__)

connectflow/vservers/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

vservers = Blueprint('vservers', __name__)

@vservers.route('/vservers')
def frame(): 
    return render_template('vservers.html')

connectflow/templates/ap.html
{% extends "base.html" %}
{% block content %}
<h1>AP</h1>
{% endblock %}

connectflow/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
    integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
    crossorigin="anonymous"></script>
  <meta charset="UTF-8">
  <title>커넥트플로우</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
  <nav class="navbar navbar-dark bg-dark">
    <!-- Navbar content -->
    <ul class="nav">
      <li class="nav-link">
        <a href="{{url_for('core.index')}}">커넥트플로우</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('ap.frame')}}">상담프로그램</a>
      </li>

      {% if current_user.is_authenticated %}
      <li class="nav-link">
        <a href="#">로그아웃</a>
      </li>
      <li class="nav-link">
        <a href="#">전화번호</a>
      </li>
      <li class="nav-link">
        <a href="#">네트워크</a>
      </li>
      <li class="nav-link">
        <a href="#">물리서버</a>
      </li>
      <li class="nav-link">
        <a href="#">가상머신</a>
      </li>
      <li class="nav-link">
        <a href="#">고객사</a>
      </li>
      <li class="nav-link">
        <a href="#">협력사</a>
      </li>
      {% else %}
      <li class="nav-link">
        <a href="#">로그인(관리자)</a>
      </li>
      <li class="nav-link">
        <a href="#">등록(관리자)</a>
      </li>
      {% endif %}
    </ul>
  </nav>


  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

connectflow/templates/customers.html
{% extends "base.html" %}
{% block content %}
<h1>CUSTOMERS</h1>
{% endblock %}

connectflow/templates/index.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <div id="card-box" class="cards-box">
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'phone_number.png')}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">전화번호</h5>
                <p class="card-text">운영중인 인터넷전화번호와 지능망전화번호를 확인 할 수 있습니다.</p>
                <a href="{{url_for('numbers.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'networks.png')}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">네트워크</h5>
                <p class="card-text">운영중인 네트워크 정보와 장치를 확인 할 수 있습니다.</p>
                <a href="{{url_for('networks.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'physical_server.png')}}" class="card-img-top"
                alt="...">
            <div class="card-body">
                <h5 class="card-title">물리서버</h5>
                <p class="card-text">운영중인 물리서버 정보를 확인 할 수 있습니다.</p>
                <a href="{{url_for('pservers.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'virtual_server.png')}}" class="card-img-top"
                alt="...">
            <div class="card-body">
                <h5 class="card-title">가상머신</h5>
                <p class="card-text">운영중인 가상머신 정보를 확인 할 수 있습니다.</p>
                <a href="{{url_for('vservers.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'customers.png')}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">고객사</h5>
                <p class="card-text">운영중인 고객사 정보를 확인 할 수 있습니다.</p>
                <a href="{{url_for('customers.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='images/card/'+'partners.png')}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">협력사</h5>
                <p class="card-text">함께하는 협력사 정보를 확인 할 수 있습니다.</p>
                <a href="{{url_for('partners.frame')}}" class="btn btn-primary">이동</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

connectflow/templates/networks.html
{% extends "base.html" %}
{% block content %}
<h1>NETWORKS</h1>
{% endblock %}

connectflow/templates/numbers.html
{% extends "base.html" %}
{% block content %}
<h1>NUMBERS</h1>
{% endblock %}

connectflow/templates/partners.html
{% extends "base.html" %}
{% block content %}
<h1>PARTNERS</h1>
{% endblock %}

connectflow/templates/vservers.html
{% extends "base.html" %}
{% block content %}
<h1>VSERVERS</h1>
{% endblock %}